//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Checkout;

interface

type
  CheckoutReview = public partial class
  protected 
    var OrderItemList: System.Web.UI.WebControls.GridView;
    var ShipInfo: System.Web.UI.WebControls.DetailsView;
    var CheckoutConfirm: System.Web.UI.WebControls.Button;
  end;
  
implementation

end.
