//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet;

interface

type
  ErrorPage = public partial class
  protected 
    var FriendlyErrorMsg: System.Web.UI.WebControls.Label;
    var DetailedErrorPanel: System.Web.UI.WebControls.Panel;
    var ErrorDetailedMsg: System.Web.UI.WebControls.Label;
    var ErrorHandler: System.Web.UI.WebControls.Label;
    var InnerMessage: System.Web.UI.WebControls.Label;
    var InnerTrace: System.Web.UI.WebControls.Label;
  end;
  
implementation

end.
