//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet;

interface

type
  Site_Mobile = public partial class
  protected 
    var HeadContent: System.Web.UI.WebControls.ContentPlaceHolder;
    var form1: System.Web.UI.HtmlControls.HtmlForm;
    var FeaturedContent: System.Web.UI.WebControls.ContentPlaceHolder;
    var MainContent: System.Web.UI.WebControls.ContentPlaceHolder;
  end;
  
implementation

end.
