//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet;

interface

type
    ShoppingCart = public partial class
    protected 
        var ShoppingCartTitle: System.Web.UI.HtmlControls.HtmlGenericControl;
        var CartList: System.Web.UI.WebControls.GridView;
        var LabelTotalText: System.Web.UI.WebControls.Label;
        var lblTotal: System.Web.UI.WebControls.Label;
        var UpdateBtn: System.Web.UI.WebControls.Button;
        var CheckoutImageBtn: System.Web.UI.WebControls.ImageButton;
    end;
    
implementation

end.
