//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Admin;

interface

type
  AdminPage = public partial class
  protected 
    var LabelAddCategory: System.Web.UI.WebControls.Label;
    var DropDownAddCategory: System.Web.UI.WebControls.DropDownList;
    var LabelAddName: System.Web.UI.WebControls.Label;
    var AddProductName: System.Web.UI.WebControls.TextBox;
    var RequiredFieldValidator1: System.Web.UI.WebControls.RequiredFieldValidator;
    var LabelAddNameMini: System.Web.UI.WebControls.Label;
    var AddProductNameMini: CKEditor.CKEditorControl;
    var LabelAddDescription: System.Web.UI.WebControls.Label;
    var AddProductDescription: CKEditor.CKEditorControl;
    var LabelAddPrice: System.Web.UI.WebControls.Label;
    var AddProductPrice: System.Web.UI.WebControls.TextBox;
    var RequiredFieldValidator3: System.Web.UI.WebControls.RequiredFieldValidator;
    var RegularExpressionValidator1: System.Web.UI.WebControls.RegularExpressionValidator;
    var LabelAddImageFile: System.Web.UI.WebControls.Label;
    var ProductImage: System.Web.UI.WebControls.FileUpload;
    var RequiredFieldValidator4: System.Web.UI.WebControls.RequiredFieldValidator;
    var AddProductButton: System.Web.UI.WebControls.Button;
    var LabelAddStatus: System.Web.UI.WebControls.Label;
    var LabelRemoveProduct: System.Web.UI.WebControls.Label;
    var DropDownRemoveProduct: System.Web.UI.WebControls.DropDownList;
    var RemoveProductButton: System.Web.UI.WebControls.Button;
    var LabelRemoveStatus: System.Web.UI.WebControls.Label;
  end;
  
implementation

end.
