//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Admin;

interface

type
  ProductEdit = public partial class
  protected 
    var LitProduct: System.Web.UI.WebControls.Literal;
    var modedit: System.Web.UI.WebControls.Panel;
    var ImageFileName: System.Web.UI.WebControls.HiddenField;
    var LabelStatus: System.Web.UI.WebControls.Label;
    var LabelProductID: System.Web.UI.WebControls.Label;
    var TXTProductID: System.Web.UI.WebControls.TextBox;
    var LabelAddCategory: System.Web.UI.WebControls.Label;
    var DropDownAddCategory: System.Web.UI.WebControls.DropDownList;
    var LabelProductName: System.Web.UI.WebControls.Label;
    var TXTProductName: System.Web.UI.WebControls.TextBox;
    var LabelProductNameMini: System.Web.UI.WebControls.Label;
    var TXTProductNameMini: CKEditor.CKEditorControl;
    var LabelProductDescription: System.Web.UI.WebControls.Label;
    var CKEditor: CKEditor.CKEditorControl;
    var LabelProductPrice: System.Web.UI.WebControls.Label;
    var TXTProductPrice: System.Web.UI.WebControls.TextBox;
    var LabelAddImageFile: System.Web.UI.WebControls.Label;
    var ProductImage: System.Web.UI.WebControls.FileUpload;
    var SaveProductButton: System.Web.UI.WebControls.Button;
  end;
  
implementation

end.
