<%@ Page Title="About" Language="Oxygene" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.pas" Inherits="NorpaNet.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
 
<asp:Image  ID="imgabout" runat="server" ImageUrl="/Images/Taru Kaukovalta.jpg" BorderStyle="None" Width="100%" />
   
<h4>Hei ja tervetuloa virtuaaliseen näyttelyyni !</h4>
<p>Olen syntyjäni Kirkkonummelainen ja maalaan öljyväreillä pienestä pitäen. Isoäiti Maija Rask opetti keramiikkaa ja taidetta Sjökullan koulun tiloissa, ja hänen ansiostaan aloitin öljymaalauksen varhain. Olen ”neljännen sukupolven taidemaalari” ja jatkan nyt perinnettä omien lasteni kanssa; yhdessä maalaminen on meille valtavan antoisaa. Löysin oman tyylini abstraktin taiteen parissa muutama vuosi sitten. Prosessi on yksinkertainen: maali, pensseli ja intuitio. Lopputulos on yhdistelmä mielialaa ja tunteita jotka saavat muotonsa kankaalla. Jokainen taulu puhuttelee katsojaa omakohtaisesti ja välittää oman sanomansa, myös minulle itselleni. Siksi annoin nimen ”Sielun Taika” ensimmäiselle näyttelylleni jonka pidin Wohlsin Kartanolla Kirkkonummella 17.4-8.5.2016. Toivon että viihdyt, ja ehkä löydät oman suosikkisi jonka haluaisit kotiin. Järjestän myös yksityisnäyttöjä atljélla. Hinnat ovat ohjeellisia ja otan mielelläni tarjouksia vastaan.</p>
<br />
<h4>Hej och välkommen till min virtuella utställning! </h4>
<p>Jag är infödd Kyrkslättbo och målar med oljefärg sen jag var ung. Mormor Maija Rask undervisade keramik och konst i Sjökulla skolas utrymmen, och tack vare henne kom jag igång med oljemålning tidigt. Jag är ”konstnär i fjärde generationen” och jag fortsätter nu familjetraditionen med mina egna barn; vi njuter av att måla tillsammans. För några år sedan hittade jag min egen stil i abstrakta verk. Prosessen är enkel: färg, pensel och intuition. Resultatet är en kombination av humör och känslor som tar form på duken. Varje tavla tilltalar betraktaren på ett personligt sett och har sitt eget budskap, också till mej själv. Därför valde jag namnet ”Själens Magi” för min första utställning som hölls på Wohls Gård i Kyrkslätt 17.4-8.5.2016. Jag hoppas att du trivs, och kanske hittar din favorit som du vill ta hem. Jag ordnar också privatvisningar  på min ateljé. Priserna är riktgivande och erbjudanden tas gärna emot.</p>
<br />
<h4>Hello and welcome to my virtual exhibit! </h4>
<p>I was born in Kirkkonummi and I'm painting with oil since a young age. My grandmother Maija Rask gave ceramics and art lessons on the premises of Sjökulla School, and thanks to her I started oil painting early. I'm an “artist in the fourth generation”, and now I continue the family tradition with my own children: we enjoy painting together very much.  I found my own style within abstract art a few years ago. The process is simple: paint, brush and intuition. The result is a combination of emotions and state of mind that take form on the canvas. Every painting appeals to the viewer in a personal way and brings its own message, also to myself. This is why I chose the name “Magic of the Soul” for my first exhibition that was held at Wohls Gård in Kirkkonummi, Finland, April 17th to May 8th 2016. I hope that you enjoy your visit, and maybe find your favorite that you want take home. A private showing at my studio in Finland is also possible. Prices are indicative and offers are more than welcome.</p>
<br />
<h4>Bonjour et bienvenu à mon exposition virtuelle!</h4> 
<p>Je suis née à Kirkkonummi et je peins à l'huile sur toile depuis ma jeunesse. Ma grand-mère Maija Rask enseignait la poterie et l'art dans les locaux de l'école Sjökulla, et c'est grâce à elle que j'ai commencé la peinture à l'huile si tôt. Je suis “artiste dans la quatrième génération“, et maintenant je continue la tradition familiale avec mes propres enfants ; nous aimions de peindre ensemble.  Il y a quelques années, j'ai trouvé mon propre style dans l'art abstrait.  Le processus est simple : de la peinture, des pinceaux et de l'intuition. Le résultat est une combinaison de l'humeur du moment et d'émotions qui prennent forme sur la toile. Chaque tableau est vu par le spectateur dans une manière personnel et porte son propre message, également à moi-même. Pour cette raison j'ai choisi “La Magie de l'Ame“ comme nom pour ma première exposition qui a eu lieu à Wohls Gård à Kirkkonummi en Finlande le 17 avril à 8 mai 2016. J'espère que vous  passez un bon moment ici, et peut-être que vous trouveriez votre favori que vous aimeriez avoir à la maison. J'organise également des visites privées à mon atelier en Finlande. Les prix affichés sont indicatifs et les offres sont les bienvenus. </p>
<p class="center"><i style="font-size:1.6em;">Taru Kaukovalta, 11.5.2016</i></p>




</asp:Content>
