//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Account;

interface

type
  ForgotPassword = public partial class
  protected 
    var loginForm: System.Web.UI.WebControls.PlaceHolder;
    var ErrorMessage: System.Web.UI.WebControls.PlaceHolder;
    var FailureText: System.Web.UI.WebControls.Literal;
    var Email: System.Web.UI.WebControls.TextBox;
    var DisplayEmail: System.Web.UI.WebControls.PlaceHolder;
  end;
  
implementation

end.
