//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Account;

interface

type
  Login = public partial class
  protected 
    var ErrorMessage: System.Web.UI.WebControls.PlaceHolder;
    var FailureText: System.Web.UI.WebControls.Literal;
    var Email: System.Web.UI.WebControls.TextBox;
    var Password: System.Web.UI.WebControls.TextBox;
    var RememberMe: System.Web.UI.WebControls.CheckBox;
    var RegisterHyperLink: System.Web.UI.WebControls.HyperLink;
    var ForgotPasswordHyperLink: System.Web.UI.WebControls.HyperLink;
    var OpenAuthLogin: NorpaNet.Account.OpenAuthProviders;
  end;
  
implementation

end.
