//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Account;

interface

type
  Manage = public partial class
  protected 
    var successMessageolder: System.Web.UI.WebControls.PlaceHolder;
    var ChangePassword: System.Web.UI.WebControls.HyperLink;
    var CreatePassword: System.Web.UI.WebControls.HyperLink;
    var PhoneAdd: System.Web.UI.WebControls.HyperLink;
    var PhoneNumber: System.Web.UI.WebControls.Label;
    var PhoneChange: System.Web.UI.WebControls.HyperLink;
    var PhoneRemove: System.Web.UI.WebControls.LinkButton;
  end;
  
implementation

end.
