//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace NorpaNet.Account;

interface

type
  ManagePassword = public partial class
  protected 
    var setPassword: System.Web.UI.WebControls.PlaceHolder;
    var password: System.Web.UI.WebControls.TextBox;
    var confirmPassword: System.Web.UI.WebControls.TextBox;
    var changePasswordHolder: System.Web.UI.WebControls.PlaceHolder;
    var CurrentPasswordLabel: System.Web.UI.WebControls.Label;
    var CurrentPassword: System.Web.UI.WebControls.TextBox;
    var NewPasswordLabel: System.Web.UI.WebControls.Label;
    var NewPassword: System.Web.UI.WebControls.TextBox;
    var ConfirmNewPasswordLabel: System.Web.UI.WebControls.Label;
    var ConfirmNewPassword: System.Web.UI.WebControls.TextBox;
  end;
  
implementation

end.
